name: Docker Build

on:
  schedule:
    - cron: "0 7 * * 1"
  push:
    branches: main

env:
  image: gabe565/ascii-telnet-rust

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Compute build variables
        id: vars
        run: |
          printf '::set-output name=short-sha::%s' "${GITHUB_SHA:0:7}"
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          pull: true
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          tags: |
            ghcr.io/${{ env.image }}:${{ steps.vars.outputs.short-sha }}
            ghcr.io/${{ env.image }}:latest
            ${{ env.image }}:${{ steps.vars.outputs.short-sha }}
            ${{ env.image }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  readme:
    name: Update DockerHub Description
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.image }}
